name       : rmlint
version    : 2.4.4
release    : 2
source     :
    - https://github.com/sahib/rmlint/archive/v2.4.4.tar.gz : 294708e7c98783a7782df1ed7f6fc79e9036571b7f69f76c5b3455545ce568bc
license    : GPL-3.0
component  : system.utils
summary    : Extremely fast tool to remove duplicates and other lint from your filesystem
description: |
    rmlint finds space waste and other broken things on your filesystem and offers to remove it.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(json-glib-1.0)
    - scons
    - python-sphinx
build      : |
    scons --prefix=$installdir/usr --actual-prefix=/usr
install    : |
    scons install --prefix=$installdir/usr --actual-prefix=/usr
