name       : rmlint
version    : 2.4.6
release    : 3
source     :
    - https://github.com/sahib/rmlint/archive/v2.4.6.tar.gz : 1ec614c38dbeb0a5d181286111ed4e37707fcd10e2c3569db0a41ef1765c5415
license    : GPL-3.0
component  : system.utils
summary    : Extremely fast tool to remove duplicates and other lint from your filesystem
description: |
    rmlint finds space waste and other broken things on your filesystem and offers to remove it.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(json-glib-1.0)
    - scons
    - python-sphinx
build      : |
    scons --prefix=$installdir/usr --actual-prefix=/usr
install    : |
    scons install --prefix=$installdir/usr --actual-prefix=/usr
