name       : rmlint
version    : 2.9.0
release    : 12
source     :
    - https://github.com/sahib/rmlint/archive/v2.9.0.tar.gz : a2d26863e0018efad60f0b1123e7cffd8ef764c8fb574a7987a49260e4e51c8f
homepage   : http://rmlint.rtfd.org
license    : GPL-3.0-or-later
component  : system.utils
summary    : Extremely fast tool to remove duplicates and other lint from your filesystem
description: |
    rmlint finds space waste and other broken things on your filesystem and offers to remove it.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libelf)
    - scons
    - python-sphinx
rundeps    :
    # Both of them are for the Shredder GUI
    - libgtksourceview3
    - python3-cairo
build      : |
    scons --prefix=$installdir/usr --actual-prefix=/usr
install    : |
    scons install --prefix=$installdir/usr --actual-prefix=/usr
    rm -f $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
