name       : rmlint
version    : 2.8.0
release    : 9
source     :
    - https://github.com/sahib/rmlint/archive/v2.8.0.tar.gz : 196bb595ac4d3d1a76ed62542b7895bda1cea47f0f77483286b2dfc8fc797253
license    : GPL-3.0-or-later
component  : system.utils
summary    : Extremely fast tool to remove duplicates and other lint from your filesystem
description: |
    rmlint finds space waste and other broken things on your filesystem and offers to remove it.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libelf)
    - scons
    - python-sphinx
rundeps    :
    # Both of them are for the Shredder GUI
        - libgtksourceview
        - python3
build      : |
    scons --prefix=$installdir/usr --actual-prefix=/usr
install    : |
    scons install --prefix=$installdir/usr --actual-prefix=/usr
