name       : rmlint
version    : 2.10.1
release    : 20
source     :
    - https://github.com/sahib/rmlint/archive/v2.10.1.tar.gz : 10e72ba4dd9672d1b6519c0c94eae647c5069c7d11f1409a46e7011dd0c6b883
homepage   : http://rmlint.rtfd.org
license    : GPL-3.0-or-later
component  : system.utils
summary    : Extremely fast tool to remove duplicates and other lint from your filesystem
description: |
    rmlint finds space waste and other broken things on your filesystem and offers to remove it.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libelf)
    - scons
    - python-sphinx
rundeps    :
    - libgtksourceview3
    - python3-cairo
build      : |
    scons --prefix=$installdir/usr --actual-prefix=/usr
install    : |
    scons install --prefix=$installdir/usr --actual-prefix=/usr
    rm -f $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
